PREFIX	=

-include makefile.prefix

#REVFILE = REVISION
TARGET  = shp_client
FLAGS = -O0 -g -ggdb

INC = -I.
LIB = 

SRCCPP := \
    main.cpp

# sources
include ../common/log/.rules
include ../common/network/.rules

# global rules
include ../common/build/.rules
